// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package schema

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Order struct {
	_tab flatbuffers.Table
}

func GetRootAsOrder(buf []byte, offset flatbuffers.UOffsetT) *Order {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Order{}
	x.Init(buf, n+offset)
	return x
}

func FinishOrderBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsOrder(buf []byte, offset flatbuffers.UOffsetT) *Order {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Order{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedOrderBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *Order) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Order) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Order) OrderId() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Order) MutateOrderId(n uint64) bool {
	return rcv._tab.MutateUint64Slot(4, n)
}

func (rcv *Order) Side() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Order) MutateSide(n byte) bool {
	return rcv._tab.MutateByteSlot(6, n)
}

func (rcv *Order) Type() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Order) MutateType(n byte) bool {
	return rcv._tab.MutateByteSlot(8, n)
}

func (rcv *Order) Price() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Order) MutatePrice(n uint64) bool {
	return rcv._tab.MutateUint64Slot(10, n)
}

func (rcv *Order) Quantity() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Order) MutateQuantity(n uint64) bool {
	return rcv._tab.MutateUint64Slot(12, n)
}

func OrderStart(builder *flatbuffers.Builder) {
	builder.StartObject(5)
}
func OrderAddOrderId(builder *flatbuffers.Builder, orderId uint64) {
	builder.PrependUint64Slot(0, orderId, 0)
}
func OrderAddSide(builder *flatbuffers.Builder, side byte) {
	builder.PrependByteSlot(1, side, 0)
}
func OrderAddType(builder *flatbuffers.Builder, type_ byte) {
	builder.PrependByteSlot(2, type_, 0)
}
func OrderAddPrice(builder *flatbuffers.Builder, price uint64) {
	builder.PrependUint64Slot(3, price, 0)
}
func OrderAddQuantity(builder *flatbuffers.Builder, quantity uint64) {
	builder.PrependUint64Slot(4, quantity, 0)
}
func OrderEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
