// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;


#[allow(unused_imports, dead_code)]
pub mod engine {

#[allow(unused_imports, dead_code)]
pub mod schema {


pub enum LevelOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct Level<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for Level<'a> {
  type Inner = Level<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> Level<'a> {
  pub const VT_PRICE: ::flatbuffers::VOffsetT = 4;
  pub const VT_QUANTITY: ::flatbuffers::VOffsetT = 6;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    Level { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args LevelArgs
  ) -> ::flatbuffers::WIPOffset<Level<'bldr>> {
    let mut builder = LevelBuilder::new(_fbb);
    builder.add_quantity(args.quantity);
    builder.add_price(args.price);
    builder.finish()
  }


  #[inline]
  pub fn price(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(Level::VT_PRICE, Some(0)).unwrap()}
  }
  #[inline]
  pub fn quantity(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(Level::VT_QUANTITY, Some(0)).unwrap()}
  }
}

impl ::flatbuffers::Verifiable for Level<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<u64>("price", Self::VT_PRICE, false)?
     .visit_field::<u64>("quantity", Self::VT_QUANTITY, false)?
     .finish();
    Ok(())
  }
}
pub struct LevelArgs {
    pub price: u64,
    pub quantity: u64,
}
impl<'a> Default for LevelArgs {
  #[inline]
  fn default() -> Self {
    LevelArgs {
      price: 0,
      quantity: 0,
    }
  }
}

pub struct LevelBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> LevelBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_price(&mut self, price: u64) {
    self.fbb_.push_slot::<u64>(Level::VT_PRICE, price, 0);
  }
  #[inline]
  pub fn add_quantity(&mut self, quantity: u64) {
    self.fbb_.push_slot::<u64>(Level::VT_QUANTITY, quantity, 0);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> LevelBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    LevelBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<Level<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for Level<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("Level");
      ds.field("price", &self.price());
      ds.field("quantity", &self.quantity());
      ds.finish()
  }
}
pub enum BookUpdateOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct BookUpdate<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for BookUpdate<'a> {
  type Inner = BookUpdate<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> BookUpdate<'a> {
  pub const VT_BID_LEVELS: ::flatbuffers::VOffsetT = 4;
  pub const VT_ASK_LEVELS: ::flatbuffers::VOffsetT = 6;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    BookUpdate { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args BookUpdateArgs<'args>
  ) -> ::flatbuffers::WIPOffset<BookUpdate<'bldr>> {
    let mut builder = BookUpdateBuilder::new(_fbb);
    if let Some(x) = args.ask_levels { builder.add_ask_levels(x); }
    if let Some(x) = args.bid_levels { builder.add_bid_levels(x); }
    builder.finish()
  }


  #[inline]
  pub fn bid_levels(&self) -> Option<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<Level<'a>>>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<Level>>>>(BookUpdate::VT_BID_LEVELS, None)}
  }
  #[inline]
  pub fn ask_levels(&self) -> Option<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<Level<'a>>>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<Level>>>>(BookUpdate::VT_ASK_LEVELS, None)}
  }
}

impl ::flatbuffers::Verifiable for BookUpdate<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, ::flatbuffers::ForwardsUOffset<Level>>>>("bid_levels", Self::VT_BID_LEVELS, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, ::flatbuffers::ForwardsUOffset<Level>>>>("ask_levels", Self::VT_ASK_LEVELS, false)?
     .finish();
    Ok(())
  }
}
pub struct BookUpdateArgs<'a> {
    pub bid_levels: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<Level<'a>>>>>,
    pub ask_levels: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<Level<'a>>>>>,
}
impl<'a> Default for BookUpdateArgs<'a> {
  #[inline]
  fn default() -> Self {
    BookUpdateArgs {
      bid_levels: None,
      ask_levels: None,
    }
  }
}

pub struct BookUpdateBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> BookUpdateBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_bid_levels(&mut self, bid_levels: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , ::flatbuffers::ForwardsUOffset<Level<'b >>>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(BookUpdate::VT_BID_LEVELS, bid_levels);
  }
  #[inline]
  pub fn add_ask_levels(&mut self, ask_levels: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , ::flatbuffers::ForwardsUOffset<Level<'b >>>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(BookUpdate::VT_ASK_LEVELS, ask_levels);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> BookUpdateBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    BookUpdateBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<BookUpdate<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for BookUpdate<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("BookUpdate");
      ds.field("bid_levels", &self.bid_levels());
      ds.field("ask_levels", &self.ask_levels());
      ds.finish()
  }
}
#[inline]
/// Verifies that a buffer of bytes contains a `BookUpdate`
/// and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_book_update_unchecked`.
pub fn root_as_book_update(buf: &[u8]) -> Result<BookUpdate<'_>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::root::<BookUpdate>(buf)
}
#[inline]
/// Verifies that a buffer of bytes contains a size prefixed
/// `BookUpdate` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `size_prefixed_root_as_book_update_unchecked`.
pub fn size_prefixed_root_as_book_update(buf: &[u8]) -> Result<BookUpdate<'_>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::size_prefixed_root::<BookUpdate>(buf)
}
#[inline]
/// Verifies, with the given options, that a buffer of bytes
/// contains a `BookUpdate` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_book_update_unchecked`.
pub fn root_as_book_update_with_opts<'b, 'o>(
  opts: &'o ::flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<BookUpdate<'b>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::root_with_opts::<BookUpdate<'b>>(opts, buf)
}
#[inline]
/// Verifies, with the given verifier options, that a buffer of
/// bytes contains a size prefixed `BookUpdate` and returns
/// it. Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_book_update_unchecked`.
pub fn size_prefixed_root_as_book_update_with_opts<'b, 'o>(
  opts: &'o ::flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<BookUpdate<'b>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::size_prefixed_root_with_opts::<BookUpdate<'b>>(opts, buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a BookUpdate and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid `BookUpdate`.
pub unsafe fn root_as_book_update_unchecked(buf: &[u8]) -> BookUpdate<'_> {
  unsafe { ::flatbuffers::root_unchecked::<BookUpdate>(buf) }
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a size prefixed BookUpdate and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid size prefixed `BookUpdate`.
pub unsafe fn size_prefixed_root_as_book_update_unchecked(buf: &[u8]) -> BookUpdate<'_> {
  unsafe { ::flatbuffers::size_prefixed_root_unchecked::<BookUpdate>(buf) }
}
#[inline]
pub fn finish_book_update_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(
    fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
    root: ::flatbuffers::WIPOffset<BookUpdate<'a>>) {
  fbb.finish(root, None);
}

#[inline]
pub fn finish_size_prefixed_book_update_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>, root: ::flatbuffers::WIPOffset<BookUpdate<'a>>) {
  fbb.finish_size_prefixed(root, None);
}
}  // pub mod schema
}  // pub mod engine

