// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;


#[allow(unused_imports, dead_code)]
pub mod engine {

#[allow(unused_imports, dead_code)]
pub mod schema {


pub enum TradeEventOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct TradeEvent<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for TradeEvent<'a> {
  type Inner = TradeEvent<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> TradeEvent<'a> {
  pub const VT_TAKER_ORDER_ID: ::flatbuffers::VOffsetT = 4;
  pub const VT_MAKER_ORDER_ID: ::flatbuffers::VOffsetT = 6;
  pub const VT_TAKER_SIDE: ::flatbuffers::VOffsetT = 8;
  pub const VT_PRICE: ::flatbuffers::VOffsetT = 10;
  pub const VT_QUANTITY: ::flatbuffers::VOffsetT = 12;
  pub const VT_SEQUENCE: ::flatbuffers::VOffsetT = 14;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    TradeEvent { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args TradeEventArgs
  ) -> ::flatbuffers::WIPOffset<TradeEvent<'bldr>> {
    let mut builder = TradeEventBuilder::new(_fbb);
    builder.add_sequence(args.sequence);
    builder.add_quantity(args.quantity);
    builder.add_price(args.price);
    builder.add_maker_order_id(args.maker_order_id);
    builder.add_taker_order_id(args.taker_order_id);
    builder.add_taker_side(args.taker_side);
    builder.finish()
  }


  #[inline]
  pub fn taker_order_id(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(TradeEvent::VT_TAKER_ORDER_ID, Some(0)).unwrap()}
  }
  #[inline]
  pub fn maker_order_id(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(TradeEvent::VT_MAKER_ORDER_ID, Some(0)).unwrap()}
  }
  #[inline]
  pub fn taker_side(&self) -> u8 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u8>(TradeEvent::VT_TAKER_SIDE, Some(0)).unwrap()}
  }
  #[inline]
  pub fn price(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(TradeEvent::VT_PRICE, Some(0)).unwrap()}
  }
  #[inline]
  pub fn quantity(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(TradeEvent::VT_QUANTITY, Some(0)).unwrap()}
  }
  #[inline]
  pub fn sequence(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(TradeEvent::VT_SEQUENCE, Some(0)).unwrap()}
  }
}

impl ::flatbuffers::Verifiable for TradeEvent<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<u64>("taker_order_id", Self::VT_TAKER_ORDER_ID, false)?
     .visit_field::<u64>("maker_order_id", Self::VT_MAKER_ORDER_ID, false)?
     .visit_field::<u8>("taker_side", Self::VT_TAKER_SIDE, false)?
     .visit_field::<u64>("price", Self::VT_PRICE, false)?
     .visit_field::<u64>("quantity", Self::VT_QUANTITY, false)?
     .visit_field::<u64>("sequence", Self::VT_SEQUENCE, false)?
     .finish();
    Ok(())
  }
}
pub struct TradeEventArgs {
    pub taker_order_id: u64,
    pub maker_order_id: u64,
    pub taker_side: u8,
    pub price: u64,
    pub quantity: u64,
    pub sequence: u64,
}
impl<'a> Default for TradeEventArgs {
  #[inline]
  fn default() -> Self {
    TradeEventArgs {
      taker_order_id: 0,
      maker_order_id: 0,
      taker_side: 0,
      price: 0,
      quantity: 0,
      sequence: 0,
    }
  }
}

pub struct TradeEventBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> TradeEventBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_taker_order_id(&mut self, taker_order_id: u64) {
    self.fbb_.push_slot::<u64>(TradeEvent::VT_TAKER_ORDER_ID, taker_order_id, 0);
  }
  #[inline]
  pub fn add_maker_order_id(&mut self, maker_order_id: u64) {
    self.fbb_.push_slot::<u64>(TradeEvent::VT_MAKER_ORDER_ID, maker_order_id, 0);
  }
  #[inline]
  pub fn add_taker_side(&mut self, taker_side: u8) {
    self.fbb_.push_slot::<u8>(TradeEvent::VT_TAKER_SIDE, taker_side, 0);
  }
  #[inline]
  pub fn add_price(&mut self, price: u64) {
    self.fbb_.push_slot::<u64>(TradeEvent::VT_PRICE, price, 0);
  }
  #[inline]
  pub fn add_quantity(&mut self, quantity: u64) {
    self.fbb_.push_slot::<u64>(TradeEvent::VT_QUANTITY, quantity, 0);
  }
  #[inline]
  pub fn add_sequence(&mut self, sequence: u64) {
    self.fbb_.push_slot::<u64>(TradeEvent::VT_SEQUENCE, sequence, 0);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> TradeEventBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    TradeEventBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<TradeEvent<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for TradeEvent<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("TradeEvent");
      ds.field("taker_order_id", &self.taker_order_id());
      ds.field("maker_order_id", &self.maker_order_id());
      ds.field("taker_side", &self.taker_side());
      ds.field("price", &self.price());
      ds.field("quantity", &self.quantity());
      ds.field("sequence", &self.sequence());
      ds.finish()
  }
}
#[inline]
/// Verifies that a buffer of bytes contains a `TradeEvent`
/// and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_trade_event_unchecked`.
pub fn root_as_trade_event(buf: &[u8]) -> Result<TradeEvent<'_>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::root::<TradeEvent>(buf)
}
#[inline]
/// Verifies that a buffer of bytes contains a size prefixed
/// `TradeEvent` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `size_prefixed_root_as_trade_event_unchecked`.
pub fn size_prefixed_root_as_trade_event(buf: &[u8]) -> Result<TradeEvent<'_>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::size_prefixed_root::<TradeEvent>(buf)
}
#[inline]
/// Verifies, with the given options, that a buffer of bytes
/// contains a `TradeEvent` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_trade_event_unchecked`.
pub fn root_as_trade_event_with_opts<'b, 'o>(
  opts: &'o ::flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<TradeEvent<'b>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::root_with_opts::<TradeEvent<'b>>(opts, buf)
}
#[inline]
/// Verifies, with the given verifier options, that a buffer of
/// bytes contains a size prefixed `TradeEvent` and returns
/// it. Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_trade_event_unchecked`.
pub fn size_prefixed_root_as_trade_event_with_opts<'b, 'o>(
  opts: &'o ::flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<TradeEvent<'b>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::size_prefixed_root_with_opts::<TradeEvent<'b>>(opts, buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a TradeEvent and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid `TradeEvent`.
pub unsafe fn root_as_trade_event_unchecked(buf: &[u8]) -> TradeEvent<'_> {
  unsafe { ::flatbuffers::root_unchecked::<TradeEvent>(buf) }
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a size prefixed TradeEvent and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid size prefixed `TradeEvent`.
pub unsafe fn size_prefixed_root_as_trade_event_unchecked(buf: &[u8]) -> TradeEvent<'_> {
  unsafe { ::flatbuffers::size_prefixed_root_unchecked::<TradeEvent>(buf) }
}
#[inline]
pub fn finish_trade_event_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(
    fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
    root: ::flatbuffers::WIPOffset<TradeEvent<'a>>) {
  fbb.finish(root, None);
}

#[inline]
pub fn finish_size_prefixed_trade_event_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>, root: ::flatbuffers::WIPOffset<TradeEvent<'a>>) {
  fbb.finish_size_prefixed(root, None);
}
}  // pub mod schema
}  // pub mod engine

